version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"  # Expose backend on port 3001
    depends_on:
      - db

  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"  # Expose frontend on port 3000

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nodejs_login}
      MYSQL_USER: ${MYSQL_USER:-Main_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Sepio_password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
